services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    # environment:
    #   - NEXT_PUBLIC_API_URL=http://localhost:8080
    #depends_on:
     # - backend

  backend:
    #build: ./
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:13
    container_name: db
    
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: notes-app
    volumes:
      - pgdata:/var/lib/postgresql/
      - ./migrations:/docker-entrypoint-initdb.d
      
volumes:
  pgdata: {}