[package]
name = "backend"
version = "0.1.0"
authors = ["Joseph Patton <josephpatton@outlook.com>"]
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "backend"

[dependencies]
actix-web = "4"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
serde_json = "1"

[dev-dependencies]
reqwest = "0.11"
actix-rt = "2"
