services:
  # frontend:
  #   container_name: frontend
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - 4200:80
  #   # environment:
  #   #   - NEXT_PUBLIC_API_URL=http://localhost:8080
  #   depends_on:
  #     - backend
  backend:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:13
    container_name: db
    
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: notes-app
    volumes:
      - pgdata:/var/lib/postgresql/
      - ./migrations:/docker-entrypoint-initdb.d
      
volumes:
  pgdata: {}